// GENERATED FILE — do not edit by hand. Run `npm run sync:catalog` to refresh.
//
// Source: https://buildstation.app/api/td2/v2/data/mx (the data backend behind mxswat's Division 2 build tool).
// The catalog is append-only and season-locked, so this snapshot ages gracefully; refresh it
// once a season. See scripts/sync-catalog.ts for why this is committed rather than fetched.

/** Changes only when the data changes, so a no-op sync produces no diff. */
export const CATALOG_CHECKSUM = "56566a938990";

export type WeaponQuality = "Exotic" | "High End" | "Named";

export type WeaponType = "Assault Rifle" | "LMG" | "Marksman Rifle" | "Pistol" | "Rifle" | "SMG" | "Shotgun";

export interface CatalogWeapon {
  name: string;
  type: WeaponType;
  quality: WeaponQuality;
}

/** Brand sets (37). Excludes the non-brand placeholder(s) used for crafted gear. */
export const BRANDS: readonly string[] = [
  "5.11 Tactical",
  "Airaldi Holdings",
  "Alps Summit Armaments",
  "Badger Tuff",
  "Belstone Armory",
  "Brazos de Arcabuz",
  "Ceska Vyroba s.r.o.",
  "China Light Industries Corporation",
  "Douglas & Harding",
  "Edelweiss GPz",
  "Electrique",
  "Empress International",
  "Fenris Group AB",
  "Gila Guard",
  "Golan Gear Ltd",
  "Grupo Sombra S.A.",
  "Habsburg Guard",
  "Hana-U Corporation",
  "Imminence Armaments",
  "Legatus S.P.A",
  "Lengmo",
  "Murakami Industries",
  "Overlord Armaments",
  "Palisade Steelworks",
  "Petrov Defense Group",
  "Providence Defense",
  "Richter & Kaiser GmbH",
  "Royal Works",
  "Shiny Monkey Gear",
  "Sokolov Concern",
  "Unit Alloys",
  "Urban Lookout",
  "Uzina Getica",
  "Walker, Harris & Co.",
  "Wyvern Wear",
  "Yaahl Gear",
  "Zwiadowka Sp. z o.o.",
];

/** Gear sets (27). */
export const GEAR_SETS: readonly string[] = [
  "Aces & Eights",
  "Aegis",
  "Breaking Point",
  "Cavalier",
  "Concentrated Company",
  "Core Strength",
  "Eclipse Protocol",
  "Foundry Bulwark",
  "Future Initiative",
  "Hard Wired",
  "Heartbreaker",
  "Hotshot",
  "Hunter's Fury",
  "Measured Assembly",
  "Negotiator's Dilemma",
  "Ongoing Directive",
  "Ortiz: Exuro",
  "Ortiz: Reficere",
  "Refactor",
  "Rigger",
  "Striker's Battlegear",
  "System Corruption",
  "Tip of the Spear",
  "Tipping Scales",
  "True Patriot",
  "Umbra Initiative",
  "Virtuoso",
];

/** Every weapon (321), deduplicated and sorted by quality, then type, then name. */
export const WEAPONS: readonly CatalogWeapon[] = [
  { name: "Agitator", type: "Assault Rifle", quality: "Exotic" },
  { name: "Caduceus", type: "Assault Rifle", quality: "Exotic" },
  { name: "Capacitor", type: "Assault Rifle", quality: "Exotic" },
  { name: "Chameleon", type: "Assault Rifle", quality: "Exotic" },
  { name: "Eagle Bearer", type: "Assault Rifle", quality: "Exotic" },
  { name: "St Elmo's Engine", type: "Assault Rifle", quality: "Exotic" },
  { name: "Strega", type: "Assault Rifle", quality: "Exotic" },
  { name: "The Bighorn - Semi-Auto Mode", type: "Assault Rifle", quality: "Exotic" },
  { name: "The Bighorn Full-Auto Mode", type: "Assault Rifle", quality: "Exotic" },
  { name: "Big Alejandro", type: "LMG", quality: "Exotic" },
  { name: "Bluescreen", type: "LMG", quality: "Exotic" },
  { name: "Bullet King", type: "LMG", quality: "Exotic" },
  { name: "Iron Lung", type: "LMG", quality: "Exotic" },
  { name: "Pakhan", type: "LMG", quality: "Exotic" },
  { name: "Pestilence", type: "LMG", quality: "Exotic" },
  { name: "Dread Edict", type: "Marksman Rifle", quality: "Exotic" },
  { name: "Mantis", type: "Marksman Rifle", quality: "Exotic" },
  { name: "Nemesis", type: "Marksman Rifle", quality: "Exotic" },
  { name: "Sacrum Imperium", type: "Marksman Rifle", quality: "Exotic" },
  { name: "Shroud", type: "Marksman Rifle", quality: "Exotic" },
  { name: "Busy Little Bee", type: "Pistol", quality: "Exotic" },
  { name: "Liberty", type: "Pistol", quality: "Exotic" },
  { name: "Mosquito", type: "Pistol", quality: "Exotic" },
  { name: "Regulus", type: "Pistol", quality: "Exotic" },
  { name: "Tempest", type: "Pistol", quality: "Exotic" },
  { name: "Whiplash", type: "Pistol", quality: "Exotic" },
  { name: "Bittersweet", type: "Rifle", quality: "Exotic" },
  { name: "Diamondback", type: "Rifle", quality: "Exotic" },
  { name: "Doctor Home", type: "Rifle", quality: "Exotic" },
  { name: "Merciless", type: "Rifle", quality: "Exotic" },
  { name: "Ruthless", type: "Rifle", quality: "Exotic" },
  { name: "The Ravenous", type: "Rifle", quality: "Exotic" },
  { name: "Vindicator", type: "Rifle", quality: "Exotic" },
  { name: "Lullaby", type: "Shotgun", quality: "Exotic" },
  { name: "Overlord", type: "Shotgun", quality: "Exotic" },
  { name: "Scorpio", type: "Shotgun", quality: "Exotic" },
  { name: "Sheriff", type: "Shotgun", quality: "Exotic" },
  { name: "Sweet Dreams", type: "Shotgun", quality: "Exotic" },
  { name: "Backfire", type: "SMG", quality: "Exotic" },
  { name: "Lady Death", type: "SMG", quality: "Exotic" },
  { name: "Ouroboros", type: "SMG", quality: "Exotic" },
  { name: "Oxpecker", type: "SMG", quality: "Exotic" },
  { name: "The Chatterbox", type: "SMG", quality: "Exotic" },
  { name: "Underboss", type: "SMG", quality: "Exotic" },
  { name: "ACR", type: "Assault Rifle", quality: "High End" },
  { name: "ACR-E", type: "Assault Rifle", quality: "High End" },
  { name: "AK-M", type: "Assault Rifle", quality: "High End" },
  { name: "AUG A3-CQC", type: "Assault Rifle", quality: "High End" },
  { name: "Black Market AK-M", type: "Assault Rifle", quality: "High End" },
  { name: "Black Market AK-M Replica", type: "Assault Rifle", quality: "High End" },
  { name: "Carbine 7", type: "Assault Rifle", quality: "High End" },
  { name: "CTAR-21", type: "Assault Rifle", quality: "High End" },
  { name: "Custom P416 G3", type: "Assault Rifle", quality: "High End" },
  { name: "F2000", type: "Assault Rifle", quality: "High End" },
  { name: "F2000 Replica", type: "Assault Rifle", quality: "High End" },
  { name: "FAL", type: "Assault Rifle", quality: "High End" },
  { name: "FAL SA-58", type: "Assault Rifle", quality: "High End" },
  { name: "FAL SA-58 Para", type: "Assault Rifle", quality: "High End" },
  { name: "FAL SA-58 Para Replica", type: "Assault Rifle", quality: "High End" },
  { name: "FAMAS 2010", type: "Assault Rifle", quality: "High End" },
  { name: "FAMAS 2010 Replica", type: "Assault Rifle", quality: "High End" },
  { name: "G36 C", type: "Assault Rifle", quality: "High End" },
  { name: "G36 Enhanced", type: "Assault Rifle", quality: "High End" },
  { name: "G36 Enhanced Replica", type: "Assault Rifle", quality: "High End" },
  { name: "Honey Badger", type: "Assault Rifle", quality: "High End" },
  { name: "Military AK-M", type: "Assault Rifle", quality: "High End" },
  { name: "Military G36", type: "Assault Rifle", quality: "High End" },
  { name: "Military P416", type: "Assault Rifle", quality: "High End" },
  { name: "Mk16", type: "Assault Rifle", quality: "High End" },
  { name: "PDR", type: "Assault Rifle", quality: "High End" },
  { name: "Police M4", type: "Assault Rifle", quality: "High End" },
  { name: "Police M4 Replica", type: "Assault Rifle", quality: "High End" },
  { name: "SIG 556", type: "Assault Rifle", quality: "High End" },
  { name: "SOCOM Mk16", type: "Assault Rifle", quality: "High End" },
  { name: "Tactical Mk 16", type: "Assault Rifle", quality: "High End" },
  { name: "Tactical Mk 16 Replica", type: "Assault Rifle", quality: "High End" },
  { name: "TKB-408", type: "Assault Rifle", quality: "High End" },
  { name: "Black Market M60 E6", type: "LMG", quality: "High End" },
  { name: "Black Market M60 E6 Replica", type: "LMG", quality: "High End" },
  { name: "Black Market RPK-74 E", type: "LMG", quality: "High End" },
  { name: "Black Market RPK-74 E Replica", type: "LMG", quality: "High End" },
  { name: "Classic M60", type: "LMG", quality: "High End" },
  { name: "Classic M60 Replica", type: "LMG", quality: "High End" },
  { name: "Classic RPK-74", type: "LMG", quality: "High End" },
  { name: "Custom L86 A2", type: "LMG", quality: "High End" },
  { name: "Custom L86 A2 Replica", type: "LMG", quality: "High End" },
  { name: "GR9", type: "LMG", quality: "High End" },
  { name: "Infantry MG5", type: "LMG", quality: "High End" },
  { name: "Infantry MG5 Replica", type: "LMG", quality: "High End" },
  { name: "IWI NEGEV", type: "LMG", quality: "High End" },
  { name: "M249 B", type: "LMG", quality: "High End" },
  { name: "MG5", type: "LMG", quality: "High End" },
  { name: "Military L86 LSW", type: "LMG", quality: "High End" },
  { name: "Military M60 E4", type: "LMG", quality: "High End" },
  { name: "Military MK46", type: "LMG", quality: "High End" },
  { name: "Military MK46 Replica", type: "LMG", quality: "High End" },
  { name: "Military RPK-74 M", type: "LMG", quality: "High End" },
  { name: "Stoner LAMG", type: "LMG", quality: "High End" },
  { name: "Tactical M249 Para", type: "LMG", quality: "High End" },
  { name: "Adrestia", type: "Marksman Rifle", quality: "High End" },
  { name: "Classic M44 Carbine", type: "Marksman Rifle", quality: "High End" },
  { name: "Classic M44 Carbine Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "Covert SRS", type: "Marksman Rifle", quality: "High End" },
  { name: "Custom M44", type: "Marksman Rifle", quality: "High End" },
  { name: "Custom M44 Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "G28", type: "Marksman Rifle", quality: "High End" },
  { name: "Hunting M44", type: "Marksman Rifle", quality: "High End" },
  { name: "M700 Carbon", type: "Marksman Rifle", quality: "High End" },
  { name: "M700 Carbon Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "M700 Tactical", type: "Marksman Rifle", quality: "High End" },
  { name: "Model 700", type: "Marksman Rifle", quality: "High End" },
  { name: "Model 700 Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "Paratrooper SVD", type: "Marksman Rifle", quality: "High End" },
  { name: "SOCOM Mk20 SSR", type: "Marksman Rifle", quality: "High End" },
  { name: "SOCOM Mk20 SSR Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "SR-1", type: "Marksman Rifle", quality: "High End" },
  { name: "SR-1 Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "SRS A1", type: "Marksman Rifle", quality: "High End" },
  { name: "SRS A1 Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "Surplus SVD", type: "Marksman Rifle", quality: "High End" },
  { name: "Tactical .308", type: "Marksman Rifle", quality: "High End" },
  { name: "586 Magnum", type: "Pistol", quality: "High End" },
  { name: "93R", type: "Pistol", quality: "High End" },
  { name: "Custom PF45", type: "Pistol", quality: "High End" },
  { name: "D50", type: "Pistol", quality: "High End" },
  { name: "Diceros", type: "Pistol", quality: "High End" },
  { name: "Diceros Replica", type: "Pistol", quality: "High End" },
  { name: "First Wave PF45", type: "Pistol", quality: "High End" },
  { name: "KARD-45", type: "Pistol", quality: "High End" },
  { name: "M1911", type: "Pistol", quality: "High End" },
  { name: "M45A1", type: "Pistol", quality: "High End" },
  { name: "Military M9", type: "Pistol", quality: "High End" },
  { name: "Military M9 Replica", type: "Pistol", quality: "High End" },
  { name: "Officer's M9 A1", type: "Pistol", quality: "High End" },
  { name: "Police 686 Magnum", type: "Pistol", quality: "High End" },
  { name: "Police 686 Magnum Replica", type: "Pistol", quality: "High End" },
  { name: "Px4 Storm Type F", type: "Pistol", quality: "High End" },
  { name: "Px4 Storm Type T", type: "Pistol", quality: "High End" },
  { name: "Px4 Storm Type T Replica", type: "Pistol", quality: "High End" },
  { name: "Snubnosed Diceros", type: "Pistol", quality: "High End" },
  { name: "Tactical M1911", type: "Pistol", quality: "High End" },
  { name: "Tactical M1911 Replica", type: "Pistol", quality: "High End" },
  { name: "X-45", type: "Pistol", quality: "High End" },
  { name: "X-45 Tactical", type: "Pistol", quality: "High End" },
  { name: "X-45 Tactical Replica", type: "Pistol", quality: "High End" },
  { name: "1886", type: "Rifle", quality: "High End" },
  { name: "ACR SS", type: "Rifle", quality: "High End" },
  { name: "Classic M1A", type: "Rifle", quality: "High End" },
  { name: "Lightweight M4", type: "Rifle", quality: "High End" },
  { name: "LVOA-C", type: "Rifle", quality: "High End" },
  { name: "LVOA-C Replica", type: "Rifle", quality: "High End" },
  { name: "M16A2", type: "Rifle", quality: "High End" },
  { name: "M16A2 Replica", type: "Rifle", quality: "High End" },
  { name: "M1A CQB", type: "Rifle", quality: "High End" },
  { name: "M1A CQB Replica", type: "Rifle", quality: "High End" },
  { name: "Military Mk17", type: "Rifle", quality: "High End" },
  { name: "Police Mk17", type: "Rifle", quality: "High End" },
  { name: "Police Mk17 Replica", type: "Rifle", quality: "High End" },
  { name: "Resolute MK47", type: "Rifle", quality: "High End" },
  { name: "SIG 716", type: "Rifle", quality: "High End" },
  { name: "SIG 716 CQB", type: "Rifle", quality: "High End" },
  { name: "SIG 716 Replica", type: "Rifle", quality: "High End" },
  { name: "SOCOM M1A", type: "Rifle", quality: "High End" },
  { name: "UIC15 MOD2", type: "Rifle", quality: "High End" },
  { name: "Urban MDR", type: "Rifle", quality: "High End" },
  { name: "Urban MDR Replica", type: "Rifle", quality: "High End" },
  { name: "USC .45 ACP", type: "Rifle", quality: "High End" },
  { name: "USC .45 ACP Replica", type: "Rifle", quality: "High End" },
  { name: "ACS-12", type: "Shotgun", quality: "High End" },
  { name: "Black Market SASG-12 S", type: "Shotgun", quality: "High End" },
  { name: "Black Market SASG-12 S Replica", type: "Shotgun", quality: "High End" },
  { name: "Custom M870 MCS", type: "Shotgun", quality: "High End" },
  { name: "Custom M870 MCS Replica", type: "Shotgun", quality: "High End" },
  { name: "Double Barrel Sawed Off", type: "Shotgun", quality: "High End" },
  { name: "Double Barrel Shotgun", type: "Shotgun", quality: "High End" },
  { name: "Double Barrel Shotgun Replica", type: "Shotgun", quality: "High End" },
  { name: "KSG Shotgun", type: "Shotgun", quality: "High End" },
  { name: "M870 Express", type: "Shotgun", quality: "High End" },
  { name: "M870 Express Replica", type: "Shotgun", quality: "High End" },
  { name: "Marine Super 90", type: "Shotgun", quality: "High End" },
  { name: "Military M870", type: "Shotgun", quality: "High End" },
  { name: "SASG-12", type: "Shotgun", quality: "High End" },
  { name: "SIX12", type: "Shotgun", quality: "High End" },
  { name: "SPAS-12", type: "Shotgun", quality: "High End" },
  { name: "SPAS-12 Replica", type: "Shotgun", quality: "High End" },
  { name: "Super 90", type: "Shotgun", quality: "High End" },
  { name: "Super 90 Replica", type: "Shotgun", quality: "High End" },
  { name: "Tactical SASG-12 K", type: "Shotgun", quality: "High End" },
  { name: "Tactical Super 90 SBS", type: "Shotgun", quality: "High End" },
  { name: "Tactical Super 90 SBS Replica", type: "Shotgun", quality: "High End" },
  { name: "AUG A3 Para XS", type: "SMG", quality: "High End" },
  { name: "Black Market T821", type: "SMG", quality: "High End" },
  { name: "Black Market T821 Replica", type: "SMG", quality: "High End" },
  { name: "CMMG Banshee", type: "SMG", quality: "High End" },
  { name: "Converted SMG-9", type: "SMG", quality: "High End" },
  { name: "Converted SMG-9 A2", type: "SMG", quality: "High End" },
  { name: "Converted SMG-9 Replica", type: "SMG", quality: "High End" },
  { name: "Enhanced AUG A3P", type: "SMG", quality: "High End" },
  { name: "Enhanced PP-19", type: "SMG", quality: "High End" },
  { name: "M1928", type: "SMG", quality: "High End" },
  { name: "MP5 ST", type: "SMG", quality: "High End" },
  { name: "MP5 ST Replica", type: "SMG", quality: "High End" },
  { name: "MP5-N", type: "SMG", quality: "High End" },
  { name: "MP5A2", type: "SMG", quality: "High End" },
  { name: "MP7", type: "SMG", quality: "High End" },
  { name: "P90", type: "SMG", quality: "High End" },
  { name: "P90 Replica", type: "SMG", quality: "High End" },
  { name: "Police T821", type: "SMG", quality: "High End" },
  { name: "Police UMP-45", type: "SMG", quality: "High End" },
  { name: "PP-19", type: "SMG", quality: "High End" },
  { name: "SIG MPX", type: "SMG", quality: "High End" },
  { name: "Tactical AUG A3P", type: "SMG", quality: "High End" },
  { name: "Tactical AUG A3P Replica", type: "SMG", quality: "High End" },
  { name: "Tactical UMP-45", type: "SMG", quality: "High End" },
  { name: "Tactical UMP-45 Replica", type: "SMG", quality: "High End" },
  { name: "Tactical Vector SBR 9mm", type: "SMG", quality: "High End" },
  { name: "Tommy Gun", type: "SMG", quality: "High End" },
  { name: "Vector SBR .45 ACP", type: "SMG", quality: "High End" },
  { name: "Vector SBR .45 ACP Replica", type: "SMG", quality: "High End" },
  { name: "Vector SBR 9mm", type: "SMG", quality: "High End" },
  { name: "Born Great", type: "Assault Rifle", quality: "Named" },
  { name: "Burn Out", type: "Assault Rifle", quality: "Named" },
  { name: "Caretaker", type: "Assault Rifle", quality: "Named" },
  { name: "First Bloom", type: "Assault Rifle", quality: "Named" },
  { name: "First Sight", type: "Assault Rifle", quality: "Named" },
  { name: "Glory Daze", type: "Assault Rifle", quality: "Named" },
  { name: "Goalie", type: "Assault Rifle", quality: "Named" },
  { name: "Huntsman", type: "Assault Rifle", quality: "Named" },
  { name: "Invisible Hand", type: "Assault Rifle", quality: "Named" },
  { name: "Kingbreaker", type: "Assault Rifle", quality: "Named" },
  { name: "Lexington", type: "Assault Rifle", quality: "Named" },
  { name: "Lud", type: "Assault Rifle", quality: "Named" },
  { name: "Manic", type: "Assault Rifle", quality: "Named" },
  { name: "Mechanical Animal", type: "Assault Rifle", quality: "Named" },
  { name: "Pyromaniac", type: "Assault Rifle", quality: "Named" },
  { name: "Savage Wolverine", type: "Assault Rifle", quality: "Named" },
  { name: "Shield Splinterer", type: "Assault Rifle", quality: "Named" },
  { name: "Test Subject", type: "Assault Rifle", quality: "Named" },
  { name: "The Archivist", type: "Assault Rifle", quality: "Named" },
  { name: "The Drill", type: "Assault Rifle", quality: "Named" },
  { name: "The Railsplitter", type: "Assault Rifle", quality: "Named" },
  { name: "Bell Ringer", type: "LMG", quality: "Named" },
  { name: "Big Show", type: "LMG", quality: "Named" },
  { name: "Black Friday", type: "LMG", quality: "Named" },
  { name: "Carnage", type: "LMG", quality: "Named" },
  { name: "Cricket", type: "LMG", quality: "Named" },
  { name: "Dare", type: "LMG", quality: "Named" },
  { name: "Gear Shift", type: "LMG", quality: "Named" },
  { name: "Good Times", type: "LMG", quality: "Named" },
  { name: "Insult To Injury", type: "LMG", quality: "Named" },
  { name: "New Reliable", type: "LMG", quality: "Named" },
  { name: "October Fifth - M249 B", type: "LMG", quality: "Named" },
  { name: "Quiet Roar", type: "LMG", quality: "Named" },
  { name: "Rusty", type: "LMG", quality: "Named" },
  { name: "Sleipnir", type: "LMG", quality: "Named" },
  { name: "Tabula Rasa", type: "LMG", quality: "Named" },
  { name: "The Stinger", type: "LMG", quality: "Named" },
  { name: "Brutus", type: "Marksman Rifle", quality: "Named" },
  { name: "Commando", type: "Marksman Rifle", quality: "Named" },
  { name: "Designated Hitter", type: "Marksman Rifle", quality: "Named" },
  { name: "Ekim's Long Stick", type: "Marksman Rifle", quality: "Named" },
  { name: "Handbasket", type: "Marksman Rifle", quality: "Named" },
  { name: "Instigator", type: "Marksman Rifle", quality: "Named" },
  { name: "Oh Carol", type: "Marksman Rifle", quality: "Named" },
  { name: "Pinprick", type: "Marksman Rifle", quality: "Named" },
  { name: "Relic", type: "Marksman Rifle", quality: "Named" },
  { name: "Scalpel", type: "Marksman Rifle", quality: "Named" },
  { name: "The Darkness", type: "Marksman Rifle", quality: "Named" },
  { name: "The White Death", type: "Marksman Rifle", quality: "Named" },
  { name: "Diceros Special", type: "Pistol", quality: "Named" },
  { name: "Lightning Rod", type: "Pistol", quality: "Named" },
  { name: "Maxim 9", type: "Pistol", quality: "Named" },
  { name: "Mozambique Special", type: "Pistol", quality: "Named" },
  { name: "Orbit", type: "Pistol", quality: "Named" },
  { name: "P320 XCompact", type: "Pistol", quality: "Named" },
  { name: "Prophet", type: "Pistol", quality: "Named" },
  { name: "Quickstep", type: "Pistol", quality: "Named" },
  { name: "Sharpshooters 93R", type: "Pistol", quality: "Named" },
  { name: "Survivalist D50", type: "Pistol", quality: "Named" },
  { name: "TDI Kard Custom", type: "Pistol", quality: "Named" },
  { name: "The Harvest", type: "Pistol", quality: "Named" },
  { name: "Achilles", type: "Rifle", quality: "Named" },
  { name: "Artist's Tool", type: "Rifle", quality: "Named" },
  { name: "Baker's Dozen", type: "Rifle", quality: "Named" },
  { name: "Brain Break", type: "Rifle", quality: "Named" },
  { name: "Cooler", type: "Rifle", quality: "Named" },
  { name: "Everlasting Gaze", type: "Rifle", quality: "Named" },
  { name: "Harmony", type: "Rifle", quality: "Named" },
  { name: "Stage Left", type: "Rifle", quality: "Named" },
  { name: "Surge", type: "Rifle", quality: "Named" },
  { name: "The Virginian", type: "Rifle", quality: "Named" },
  { name: "Trader", type: "Rifle", quality: "Named" },
  { name: "Whisper", type: "Rifle", quality: "Named" },
  { name: "Backup Boomstick", type: "Shotgun", quality: "Named" },
  { name: "Boomstick", type: "Shotgun", quality: "Named" },
  { name: "Cuélebre", type: "Shotgun", quality: "Named" },
  { name: "Enforcer", type: "Shotgun", quality: "Named" },
  { name: "Firestarter", type: "Shotgun", quality: "Named" },
  { name: "Lefty", type: "Shotgun", quality: "Named" },
  { name: "Like Glue", type: "Shotgun", quality: "Named" },
  { name: "Lockdown", type: "Shotgun", quality: "Named" },
  { name: "Rock n' Roll", type: "Shotgun", quality: "Named" },
  { name: "Stack Broker", type: "Shotgun", quality: "Named" },
  { name: "The Mop", type: "Shotgun", quality: "Named" },
  { name: "The Send-Off", type: "Shotgun", quality: "Named" },
  { name: "Thorn", type: "Shotgun", quality: "Named" },
  { name: "Tsunami", type: "Shotgun", quality: "Named" },
  { name: "Cabaret", type: "SMG", quality: "Named" },
  { name: "Cold Relations", type: "SMG", quality: "Named" },
  { name: "Dark Winter", type: "SMG", quality: "Named" },
  { name: "Emeline's Guard", type: "SMG", quality: "Named" },
  { name: "Froth", type: "SMG", quality: "Named" },
  { name: "Grown Great", type: "SMG", quality: "Named" },
  { name: "Interchange", type: "SMG", quality: "Named" },
  { name: "Purist", type: "SMG", quality: "Named" },
  { name: "Safety Distance", type: "SMG", quality: "Named" },
  { name: "Slingshot", type: "SMG", quality: "Named" },
  { name: "Swap Chain", type: "SMG", quality: "Named" },
  { name: "The Apartment", type: "SMG", quality: "Named" },
  { name: "The Grudge", type: "SMG", quality: "Named" },
  { name: "The Sleigher", type: "SMG", quality: "Named" },
];
