// GENERATED FILE — do not edit by hand. Run `npm run sync:catalog` to refresh.
//
// Source: https://buildstation.app/api/td2/v2/data/mx (the data backend behind mxswat's Division 2 build tool).
// The catalog is append-only and season-locked, so this snapshot ages gracefully; refresh it
// once a season. See scripts/sync-catalog.ts for why this is committed rather than fetched.

/** Changes only when the data changes, so a no-op sync produces no diff. */
export const CATALOG_CHECKSUM = "da586123e75f";

export type WeaponQuality = "Exotic" | "High End" | "Named";

export type WeaponType = "Assault Rifle" | "LMG" | "Marksman Rifle" | "Pistol" | "Rifle" | "SMG" | "Shotgun";

export interface CatalogWeapon {
  name: string;
  type: WeaponType;
  quality: WeaponQuality;
}

/** Brand sets (37). Excludes the non-brand placeholder(s) used for crafted gear. */
export const BRANDS: readonly string[] = [
  "5.11 Tactical",
  "Airaldi Holdings",
  "Alps Summit Armaments",
  "Badger Tuff",
  "Belstone Armory",
  "Brazos de Arcabuz",
  "Ceska Vyroba s.r.o.",
  "China Light Industries Corporation",
  "Douglas & Harding",
  "Edelweiss GPz",
  "Electrique",
  "Empress International",
  "Fenris Group AB",
  "Gila Guard",
  "Golan Gear Ltd",
  "Grupo Sombra S.A.",
  "Habsburg Guard",
  "Hana-U Corporation",
  "Imminence Armaments",
  "Legatus S.P.A",
  "Lengmo",
  "Murakami Industries",
  "Overlord Armaments",
  "Palisade Steelworks",
  "Petrov Defense Group",
  "Providence Defense",
  "Richter & Kaiser GmbH",
  "Royal Works",
  "Shiny Monkey Gear",
  "Sokolov Concern",
  "Unit Alloys",
  "Urban Lookout",
  "Uzina Getica",
  "Walker, Harris & Co.",
  "Wyvern Wear",
  "Yaahl Gear",
  "Zwiadowka Sp. z o.o.",
];

/** Gear sets (27). */
export const GEAR_SETS: readonly string[] = [
  "Aces & Eights",
  "Aegis",
  "Breaking Point",
  "Cavalier",
  "Concentrated Company",
  "Core Strength",
  "Eclipse Protocol",
  "Foundry Bulwark",
  "Future Initiative",
  "Hard Wired",
  "Heartbreaker",
  "Hotshot",
  "Hunter's Fury",
  "Measured Assembly",
  "Negotiator's Dilemma",
  "Ongoing Directive",
  "Ortiz: Exuro",
  "Ortiz: Reficere",
  "Refactor",
  "Rigger",
  "Striker's Battlegear",
  "System Corruption",
  "Tip of the Spear",
  "Tipping Scales",
  "True Patriot",
  "Umbra Initiative",
  "Virtuoso",
];

/** Every weapon (321), deduplicated and sorted by quality, then type, then name. */
export const WEAPONS: readonly CatalogWeapon[] = [
  { name: "Agitator", type: "Assault Rifle", quality: "Exotic" },
  { name: "Caduceus", type: "Assault Rifle", quality: "Exotic" },
  { name: "Capacitor", type: "Assault Rifle", quality: "Exotic" },
  { name: "Chameleon", type: "Assault Rifle", quality: "Exotic" },
  { name: "Eagle Bearer", type: "Assault Rifle", quality: "Exotic" },
  { name: "St Elmo's Engine", type: "Assault Rifle", quality: "Exotic" },
  { name: "Strega", type: "Assault Rifle", quality: "Exotic" },
  { name: "The Bighorn - Semi-Auto Mode", type: "Assault Rifle", quality: "Exotic" },
  { name: "The Bighorn Full-Auto Mode", type: "Assault Rifle", quality: "Exotic" },
  { name: "Big Alejandro", type: "LMG", quality: "Exotic" },
  { name: "Bluescreen", type: "LMG", quality: "Exotic" },
  { name: "Bullet King", type: "LMG", quality: "Exotic" },
  { name: "Iron Lung", type: "LMG", quality: "Exotic" },
  { name: "Pakhan", type: "LMG", quality: "Exotic" },
  { name: "Pestilence", type: "LMG", quality: "Exotic" },
  { name: "Dread Edict", type: "Marksman Rifle", quality: "Exotic" },
  { name: "Mantis", type: "Marksman Rifle", quality: "Exotic" },
  { name: "Nemesis", type: "Marksman Rifle", quality: "Exotic" },
  { name: "Sacrum Imperium", type: "Marksman Rifle", quality: "Exotic" },
  { name: "Shroud", type: "Marksman Rifle", quality: "Exotic" },
  { name: "Busy Little Bee", type: "Pistol", quality: "Exotic" },
  { name: "Liberty", type: "Pistol", quality: "Exotic" },
  { name: "Mosquito", type: "Pistol", quality: "Exotic" },
  { name: "Regulus", type: "Pistol", quality: "Exotic" },
  { name: "Tempest", type: "Pistol", quality: "Exotic" },
  { name: "Whiplash", type: "Pistol", quality: "Exotic" },
  { name: "Bittersweet", type: "Rifle", quality: "Exotic" },
  { name: "Diamondback", type: "Rifle", quality: "Exotic" },
  { name: "Doctor Home", type: "Rifle", quality: "Exotic" },
  { name: "Merciless", type: "Rifle", quality: "Exotic" },
  { name: "Ruthless", type: "Rifle", quality: "Exotic" },
  { name: "The Ravenous", type: "Rifle", quality: "Exotic" },
  { name: "Vindicator", type: "Rifle", quality: "Exotic" },
  { name: "Lullaby", type: "Shotgun", quality: "Exotic" },
  { name: "Overlord", type: "Shotgun", quality: "Exotic" },
  { name: "Scorpio", type: "Shotgun", quality: "Exotic" },
  { name: "Sheriff", type: "Shotgun", quality: "Exotic" },
  { name: "Sweet Dreams", type: "Shotgun", quality: "Exotic" },
  { name: "Backfire", type: "SMG", quality: "Exotic" },
  { name: "Lady Death", type: "SMG", quality: "Exotic" },
  { name: "Ouroboros", type: "SMG", quality: "Exotic" },
  { name: "Oxpecker", type: "SMG", quality: "Exotic" },
  { name: "The Chatterbox", type: "SMG", quality: "Exotic" },
  { name: "Underboss", type: "SMG", quality: "Exotic" },
  { name: "ACR", type: "Assault Rifle", quality: "High End" },
  { name: "ACR-E", type: "Assault Rifle", quality: "High End" },
  { name: "AK-M", type: "Assault Rifle", quality: "High End" },
  { name: "AUG A3-CQC", type: "Assault Rifle", quality: "High End" },
  { name: "Black Market AK-M", type: "Assault Rifle", quality: "High End" },
  { name: "Black Market AK-M Replica", type: "Assault Rifle", quality: "High End" },
  { name: "Carbine 7", type: "Assault Rifle", quality: "High End" },
  { name: "CTAR-21", type: "Assault Rifle", quality: "High End" },
  { name: "Custom P416 G3", type: "Assault Rifle", quality: "High End" },
  { name: "F2000", type: "Assault Rifle", quality: "High End" },
  { name: "F2000 Replica", type: "Assault Rifle", quality: "High End" },
  { name: "FAL", type: "Assault Rifle", quality: "High End" },
  { name: "FAL SA-58", type: "Assault Rifle", quality: "High End" },
  { name: "FAL SA-58 Para", type: "Assault Rifle", quality: "High End" },
  { name: "FAL SA-58 Para Replica", type: "Assault Rifle", quality: "High End" },
  { name: "FAMAS 2010", type: "Assault Rifle", quality: "High End" },
  { name: "FAMAS 2010 Replica", type: "Assault Rifle", quality: "High End" },
  { name: "G36 C", type: "Assault Rifle", quality: "High End" },
  { name: "G36 Enhanced", type: "Assault Rifle", quality: "High End" },
  { name: "G36 Enhanced Replica", type: "Assault Rifle", quality: "High End" },
  { name: "Honey Badger", type: "Assault Rifle", quality: "High End" },
  { name: "Military AK-M", type: "Assault Rifle", quality: "High End" },
  { name: "Military G36", type: "Assault Rifle", quality: "High End" },
  { name: "Military P416", type: "Assault Rifle", quality: "High End" },
  { name: "Mk16", type: "Assault Rifle", quality: "High End" },
  { name: "PDR", type: "Assault Rifle", quality: "High End" },
  { name: "Police M4", type: "Assault Rifle", quality: "High End" },
  { name: "Police M4 Replica", type: "Assault Rifle", quality: "High End" },
  { name: "SIG 556", type: "Assault Rifle", quality: "High End" },
  { name: "SOCOM Mk16", type: "Assault Rifle", quality: "High End" },
  { name: "Tactical Mk 16", type: "Assault Rifle", quality: "High End" },
  { name: "Tactical Mk 16 Replica", type: "Assault Rifle", quality: "High End" },
  { name: "TKB-408", type: "Assault Rifle", quality: "High End" },
  { name: "Black Market M60 E6", type: "LMG", quality: "High End" },
  { name: "Black Market M60 E6 Replica", type: "LMG", quality: "High End" },
  { name: "Black Market RPK-74 E", type: "LMG", quality: "High End" },
  { name: "Black Market RPK-74 E Replica", type: "LMG", quality: "High End" },
  { name: "Classic M60", type: "LMG", quality: "High End" },
  { name: "Classic M60 Replica", type: "LMG", quality: "High End" },
  { name: "Classic RPK-74", type: "LMG", quality: "High End" },
  { name: "Custom L86 A2", type: "LMG", quality: "High End" },
  { name: "Custom L86 A2 Replica", type: "LMG", quality: "High End" },
  { name: "GR9", type: "LMG", quality: "High End" },
  { name: "Infantry MG5", type: "LMG", quality: "High End" },
  { name: "Infantry MG5 Replica", type: "LMG", quality: "High End" },
  { name: "IWI NEGEV", type: "LMG", quality: "High End" },
  { name: "M249 B", type: "LMG", quality: "High End" },
  { name: "MG5", type: "LMG", quality: "High End" },
  { name: "Military L86 LSW", type: "LMG", quality: "High End" },
  { name: "Military M60 E4", type: "LMG", quality: "High End" },
  { name: "Military MK46", type: "LMG", quality: "High End" },
  { name: "Military MK46 Replica", type: "LMG", quality: "High End" },
  { name: "Military RPK-74 M", type: "LMG", quality: "High End" },
  { name: "Stoner LAMG", type: "LMG", quality: "High End" },
  { name: "Tactical M249 Para", type: "LMG", quality: "High End" },
  { name: "Adrestia", type: "Marksman Rifle", quality: "High End" },
  { name: "Classic M44 Carbine", type: "Marksman Rifle", quality: "High End" },
  { name: "Classic M44 Carbine Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "Covert SRS", type: "Marksman Rifle", quality: "High End" },
  { name: "Custom M44", type: "Marksman Rifle", quality: "High End" },
  { name: "Custom M44 Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "G28", type: "Marksman Rifle", quality: "High End" },
  { name: "Hunting M44", type: "Marksman Rifle", quality: "High End" },
  { name: "M700 Carbon", type: "Marksman Rifle", quality: "High End" },
  { name: "M700 Carbon Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "M700 Tactical", type: "Marksman Rifle", quality: "High End" },
  { name: "Model 700", type: "Marksman Rifle", quality: "High End" },
  { name: "Model 700 Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "Paratrooper SVD", type: "Marksman Rifle", quality: "High End" },
  { name: "SOCOM Mk20 SSR", type: "Marksman Rifle", quality: "High End" },
  { name: "SOCOM Mk20 SSR Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "SR-1", type: "Marksman Rifle", quality: "High End" },
  { name: "SR-1 Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "SRS A1", type: "Marksman Rifle", quality: "High End" },
  { name: "SRS A1 Replica", type: "Marksman Rifle", quality: "High End" },
  { name: "Surplus SVD", type: "Marksman Rifle", quality: "High End" },
  { name: "Tactical .308", type: "Marksman Rifle", quality: "High End" },
  { name: "586 Magnum", type: "Pistol", quality: "High End" },
  { name: "93R", type: "Pistol", quality: "High End" },
  { name: "Custom PF45", type: "Pistol", quality: "High End" },
  { name: "D50", type: "Pistol", quality: "High End" },
  { name: "Diceros", type: "Pistol", quality: "High End" },
  { name: "Diceros Replica", type: "Pistol", quality: "High End" },
  { name: "First Wave PF45", type: "Pistol", quality: "High End" },
  { name: "KARD-45", type: "Pistol", quality: "High End" },
  { name: "M1911", type: "Pistol", quality: "High End" },
  { name: "M45A1", type: "Pistol", quality: "High End" },
  { name: "Military M9", type: "Pistol", quality: "High End" },
  { name: "Military M9 Replica", type: "Pistol", quality: "High End" },
  { name: "Officer's M9 A1", type: "Pistol", quality: "High End" },
  { name: "Police 686 Magnum", type: "Pistol", quality: "High End" },
  { name: "Police 686 Magnum Replica", type: "Pistol", quality: "High End" },
  { name: "Px4 Storm Type F", type: "Pistol", quality: "High End" },
  { name: "Px4 Storm Type T", type: "Pistol", quality: "High End" },
  { name: "Px4 Storm Type T Replica", type: "Pistol", quality: "High End" },
  { name: "Snubnosed Diceros", type: "Pistol", quality: "High End" },
  { name: "Tactical M1911", type: "Pistol", quality: "High End" },
  { name: "Tactical M1911 Replica", type: "Pistol", quality: "High End" },
  { name: "X-45", type: "Pistol", quality: "High End" },
  { name: "X-45 Tactical", type: "Pistol", quality: "High End" },
  { name: "X-45 Tactical Replica", type: "Pistol", quality: "High End" },
  { name: "1886", type: "Rifle", quality: "High End" },
  { name: "ACR SS", type: "Rifle", quality: "High End" },
  { name: "Classic M1A", type: "Rifle", quality: "High End" },
  { name: "Lightweight M4", type: "Rifle", quality: "High End" },
  { name: "LVOA-C", type: "Rifle", quality: "High End" },
  { name: "LVOA-C Replica", type: "Rifle", quality: "High End" },
  { name: "M16A2", type: "Rifle", quality: "High End" },
  { name: "M16A2 Replica", type: "Rifle", quality: "High End" },
  { name: "M1A CQB", type: "Rifle", quality: "High End" },
  { name: "M1A CQB Replica", type: "Rifle", quality: "High End" },
  { name: "Military Mk17", type: "Rifle", quality: "High End" },
  { name: "Police Mk17", type: "Rifle", quality: "High End" },
  { name: "Police Mk17 Replica", type: "Rifle", quality: "High End" },
  { name: "Resolute MK47", type: "Rifle", quality: "High End" },
  { name: "SIG 716", type: "Rifle", quality: "High End" },
  { name: "SIG 716 CQB", type: "Rifle", quality: "High End" },
  { name: "SIG 716 Replica", type: "Rifle", quality: "High End" },
  { name: "SOCOM M1A", type: "Rifle", quality: "High End" },
  { name: "UIC15 MOD2", type: "Rifle", quality: "High End" },
  { name: "Urban MDR", type: "Rifle", quality: "High End" },
  { name: "Urban MDR Replica", type: "Rifle", quality: "High End" },
  { name: "USC .45 ACP", type: "Rifle", quality: "High End" },
  { name: "USC .45 ACP Replica", type: "Rifle", quality: "High End" },
  { name: "ACS-12", type: "Shotgun", quality: "High End" },
  { name: "Black Market SASG-12 S", type: "Shotgun", quality: "High End" },
  { name: "Black Market SASG-12 S Replica", type: "Shotgun", quality: "High End" },
  { name: "Custom M870 MCS", type: "Shotgun", quality: "High End" },
  { name: "Custom M870 MCS Replica", type: "Shotgun", quality: "High End" },
  { name: "Double Barrel Sawed Off", type: "Shotgun", quality: "High End" },
  { name: "Double Barrel Shotgun", type: "Shotgun", quality: "High End" },
  { name: "Double Barrel Shotgun Replica", type: "Shotgun", quality: "High End" },
  { name: "KSG Shotgun", type: "Shotgun", quality: "High End" },
  { name: "M870 Express", type: "Shotgun", quality: "High End" },
  { name: "M870 Express Replica", type: "Shotgun", quality: "High End" },
  { name: "Marine Super 90", type: "Shotgun", quality: "High End" },
  { name: "Military M870", type: "Shotgun", quality: "High End" },
  { name: "SASG-12", type: "Shotgun", quality: "High End" },
  { name: "SIX12", type: "Shotgun", quality: "High End" },
  { name: "SPAS-12", type: "Shotgun", quality: "High End" },
  { name: "SPAS-12 Replica", type: "Shotgun", quality: "High End" },
  { name: "Super 90", type: "Shotgun", quality: "High End" },
  { name: "Super 90 Replica", type: "Shotgun", quality: "High End" },
  { name: "Tactical SASG-12 K", type: "Shotgun", quality: "High End" },
  { name: "Tactical Super 90 SBS", type: "Shotgun", quality: "High End" },
  { name: "Tactical Super 90 SBS Replica", type: "Shotgun", quality: "High End" },
  { name: "AUG A3 Para XS", type: "SMG", quality: "High End" },
  { name: "Black Market T821", type: "SMG", quality: "High End" },
  { name: "Black Market T821 Replica", type: "SMG", quality: "High End" },
  { name: "CMMG Banshee", type: "SMG", quality: "High End" },
  { name: "Converted SMG-9", type: "SMG", quality: "High End" },
  { name: "Converted SMG-9 A2", type: "SMG", quality: "High End" },
  { name: "Converted SMG-9 Replica", type: "SMG", quality: "High End" },
  { name: "Enhanced AUG A3P", type: "SMG", quality: "High End" },
  { name: "Enhanced PP-19", type: "SMG", quality: "High End" },
  { name: "M1928", type: "SMG", quality: "High End" },
  { name: "MP5 ST", type: "SMG", quality: "High End" },
  { name: "MP5 ST Replica", type: "SMG", quality: "High End" },
  { name: "MP5-N", type: "SMG", quality: "High End" },
  { name: "MP5A2", type: "SMG", quality: "High End" },
  { name: "MP7", type: "SMG", quality: "High End" },
  { name: "P90", type: "SMG", quality: "High End" },
  { name: "P90 Replica", type: "SMG", quality: "High End" },
  { name: "Police T821", type: "SMG", quality: "High End" },
  { name: "Police UMP-45", type: "SMG", quality: "High End" },
  { name: "PP-19", type: "SMG", quality: "High End" },
  { name: "SIG MPX", type: "SMG", quality: "High End" },
  { name: "Tactical AUG A3P", type: "SMG", quality: "High End" },
  { name: "Tactical AUG A3P Replica", type: "SMG", quality: "High End" },
  { name: "Tactical UMP-45", type: "SMG", quality: "High End" },
  { name: "Tactical UMP-45 Replica", type: "SMG", quality: "High End" },
  { name: "Tactical Vector SBR 9mm", type: "SMG", quality: "High End" },
  { name: "Tommy Gun", type: "SMG", quality: "High End" },
  { name: "Vector SBR .45 ACP", type: "SMG", quality: "High End" },
  { name: "Vector SBR .45 ACP Replica", type: "SMG", quality: "High End" },
  { name: "Vector SBR 9mm", type: "SMG", quality: "High End" },
  { name: "Born Great", type: "Assault Rifle", quality: "Named" },
  { name: "Burn Out", type: "Assault Rifle", quality: "Named" },
  { name: "Caretaker", type: "Assault Rifle", quality: "Named" },
  { name: "First Bloom", type: "Assault Rifle", quality: "Named" },
  { name: "First Sight", type: "Assault Rifle", quality: "Named" },
  { name: "Glory Daze", type: "Assault Rifle", quality: "Named" },
  { name: "Goalie", type: "Assault Rifle", quality: "Named" },
  { name: "Huntsman", type: "Assault Rifle", quality: "Named" },
  { name: "Invisible Hand", type: "Assault Rifle", quality: "Named" },
  { name: "Kingbreaker", type: "Assault Rifle", quality: "Named" },
  { name: "Lexington", type: "Assault Rifle", quality: "Named" },
  { name: "Lud", type: "Assault Rifle", quality: "Named" },
  { name: "Manic", type: "Assault Rifle", quality: "Named" },
  { name: "Mechanical Animal", type: "Assault Rifle", quality: "Named" },
  { name: "Pyromaniac", type: "Assault Rifle", quality: "Named" },
  { name: "Savage Wolverine", type: "Assault Rifle", quality: "Named" },
  { name: "Shield Splinterer", type: "Assault Rifle", quality: "Named" },
  { name: "Test Subject", type: "Assault Rifle", quality: "Named" },
  { name: "The Archivist", type: "Assault Rifle", quality: "Named" },
  { name: "The Drill", type: "Assault Rifle", quality: "Named" },
  { name: "The Railsplitter", type: "Assault Rifle", quality: "Named" },
  { name: "Bell Ringer", type: "LMG", quality: "Named" },
  { name: "Big Show", type: "LMG", quality: "Named" },
  { name: "Black Friday", type: "LMG", quality: "Named" },
  { name: "Carnage", type: "LMG", quality: "Named" },
  { name: "Cricket", type: "LMG", quality: "Named" },
  { name: "Dare", type: "LMG", quality: "Named" },
  { name: "Gear Shift", type: "LMG", quality: "Named" },
  { name: "Good Times", type: "LMG", quality: "Named" },
  { name: "Insult To Injury", type: "LMG", quality: "Named" },
  { name: "New Reliable", type: "LMG", quality: "Named" },
  { name: "October Fifth - M249 B", type: "LMG", quality: "Named" },
  { name: "Quiet Roar", type: "LMG", quality: "Named" },
  { name: "Rusty", type: "LMG", quality: "Named" },
  { name: "Sleipnir", type: "LMG", quality: "Named" },
  { name: "Tabula Rasa", type: "LMG", quality: "Named" },
  { name: "The Stinger", type: "LMG", quality: "Named" },
  { name: "Brutus", type: "Marksman Rifle", quality: "Named" },
  { name: "Commando", type: "Marksman Rifle", quality: "Named" },
  { name: "Designated Hitter", type: "Marksman Rifle", quality: "Named" },
  { name: "Ekim's Long Stick", type: "Marksman Rifle", quality: "Named" },
  { name: "Handbasket", type: "Marksman Rifle", quality: "Named" },
  { name: "Instigator", type: "Marksman Rifle", quality: "Named" },
  { name: "Oh Carol", type: "Marksman Rifle", quality: "Named" },
  { name: "Pinprick", type: "Marksman Rifle", quality: "Named" },
  { name: "Relic", type: "Marksman Rifle", quality: "Named" },
  { name: "Scalpel", type: "Marksman Rifle", quality: "Named" },
  { name: "The Darkness", type: "Marksman Rifle", quality: "Named" },
  { name: "The White Death", type: "Marksman Rifle", quality: "Named" },
  { name: "Diceros Special", type: "Pistol", quality: "Named" },
  { name: "Lightning Rod", type: "Pistol", quality: "Named" },
  { name: "Maxim 9", type: "Pistol", quality: "Named" },
  { name: "Mozambique Special", type: "Pistol", quality: "Named" },
  { name: "Orbit", type: "Pistol", quality: "Named" },
  { name: "P320 XCompact", type: "Pistol", quality: "Named" },
  { name: "Prophet", type: "Pistol", quality: "Named" },
  { name: "Quickstep", type: "Pistol", quality: "Named" },
  { name: "Sharpshooters 93R", type: "Pistol", quality: "Named" },
  { name: "Survivalist D50", type: "Pistol", quality: "Named" },
  { name: "TDI Kard Custom", type: "Pistol", quality: "Named" },
  { name: "The Harvest", type: "Pistol", quality: "Named" },
  { name: "Achilles", type: "Rifle", quality: "Named" },
  { name: "Artist's Tool", type: "Rifle", quality: "Named" },
  { name: "Baker's Dozen", type: "Rifle", quality: "Named" },
  { name: "Brain Break", type: "Rifle", quality: "Named" },
  { name: "Cooler", type: "Rifle", quality: "Named" },
  { name: "Everlasting Gaze", type: "Rifle", quality: "Named" },
  { name: "Harmony", type: "Rifle", quality: "Named" },
  { name: "Stage Left", type: "Rifle", quality: "Named" },
  { name: "Surge", type: "Rifle", quality: "Named" },
  { name: "The Virginian", type: "Rifle", quality: "Named" },
  { name: "Trader", type: "Rifle", quality: "Named" },
  { name: "Whisper", type: "Rifle", quality: "Named" },
  { name: "Backup Boomstick", type: "Shotgun", quality: "Named" },
  { name: "Boomstick", type: "Shotgun", quality: "Named" },
  { name: "Cuélebre", type: "Shotgun", quality: "Named" },
  { name: "Enforcer", type: "Shotgun", quality: "Named" },
  { name: "Firestarter", type: "Shotgun", quality: "Named" },
  { name: "Lefty", type: "Shotgun", quality: "Named" },
  { name: "Like Glue", type: "Shotgun", quality: "Named" },
  { name: "Lockdown", type: "Shotgun", quality: "Named" },
  { name: "Rock n' Roll", type: "Shotgun", quality: "Named" },
  { name: "Stack Broker", type: "Shotgun", quality: "Named" },
  { name: "The Mop", type: "Shotgun", quality: "Named" },
  { name: "The Send-Off", type: "Shotgun", quality: "Named" },
  { name: "Thorn", type: "Shotgun", quality: "Named" },
  { name: "Tsunami", type: "Shotgun", quality: "Named" },
  { name: "Cabaret", type: "SMG", quality: "Named" },
  { name: "Cold Relations", type: "SMG", quality: "Named" },
  { name: "Dark Winter", type: "SMG", quality: "Named" },
  { name: "Emeline's Guard", type: "SMG", quality: "Named" },
  { name: "Froth", type: "SMG", quality: "Named" },
  { name: "Grown Great", type: "SMG", quality: "Named" },
  { name: "Interchange", type: "SMG", quality: "Named" },
  { name: "Purist", type: "SMG", quality: "Named" },
  { name: "Safety Distance", type: "SMG", quality: "Named" },
  { name: "Slingshot", type: "SMG", quality: "Named" },
  { name: "Swap Chain", type: "SMG", quality: "Named" },
  { name: "The Apartment", type: "SMG", quality: "Named" },
  { name: "The Grudge", type: "SMG", quality: "Named" },
  { name: "The Sleigher", type: "SMG", quality: "Named" },
];

export type GearSlot = "Backpack" | "Chest" | "Gloves" | "Holster" | "Kneepads" | "Mask";

export type GearQuality = "Exotic" | "Named";

export interface CatalogGear {
  name: string;
  slot: GearSlot;
  quality: GearQuality;
}

/**
 * Named and Exotic gear pieces (97).
 *
 * High End and Gearset rows are excluded on purpose: upstream lists those by brand or set name
 * rather than item name, and those names already live in BRANDS and GEAR_SETS.
 */
export const GEAR: readonly CatalogGear[] = [
  { name: "Acosta's Go-Bag", slot: "Backpack", quality: "Exotic" },
  { name: "Birdie’s Quick Fix", slot: "Backpack", quality: "Exotic" },
  { name: "Harrier Pride", slot: "Backpack", quality: "Exotic" },
  { name: "Memento", slot: "Backpack", quality: "Exotic" },
  { name: "NinjaBike Messenger Bag", slot: "Backpack", quality: "Exotic" },
  { name: "Beacon", slot: "Chest", quality: "Exotic" },
  { name: "Collector", slot: "Chest", quality: "Exotic" },
  { name: "Provocator", slot: "Chest", quality: "Exotic" },
  { name: "Ridgeway's Pride", slot: "Chest", quality: "Exotic" },
  { name: "Tardigrade Armor System", slot: "Chest", quality: "Exotic" },
  { name: "Bloody Knuckles", slot: "Gloves", quality: "Exotic" },
  { name: "BTSU Gloves", slot: "Gloves", quality: "Exotic" },
  { name: "Exodus", slot: "Gloves", quality: "Exotic" },
  { name: "Overdogs", slot: "Gloves", quality: "Exotic" },
  { name: "Rugged Gauntlets", slot: "Gloves", quality: "Exotic" },
  { name: "Centurion's Scabbard", slot: "Holster", quality: "Exotic" },
  { name: "Dodge City Gunslinger's Holster", slot: "Holster", quality: "Exotic" },
  { name: "Imperial Dynasty", slot: "Holster", quality: "Exotic" },
  { name: "Nimble Holster", slot: "Holster", quality: "Exotic" },
  { name: "Shocker Punch", slot: "Holster", quality: "Exotic" },
  { name: "Waveform", slot: "Holster", quality: "Exotic" },
  { name: "Acosta's Kneepads", slot: "Kneepads", quality: "Exotic" },
  { name: "Blacklisters", slot: "Kneepads", quality: "Exotic" },
  { name: "NinjaBike Messenger Kneepads", slot: "Kneepads", quality: "Exotic" },
  { name: "Nurse’s Kneepads", slot: "Kneepads", quality: "Exotic" },
  { name: "Sawyer's Kneepads", slot: "Kneepads", quality: "Exotic" },
  { name: "Catharsis", slot: "Mask", quality: "Exotic" },
  { name: "Coyote's Mask", slot: "Mask", quality: "Exotic" },
  { name: "Investor", slot: "Mask", quality: "Exotic" },
  { name: "The Catalyst", slot: "Mask", quality: "Exotic" },
  { name: "Tinkerer", slot: "Mask", quality: "Exotic" },
  { name: "Vile", slot: "Mask", quality: "Exotic" },
  { name: "Anarchist's Cookbook", slot: "Backpack", quality: "Named" },
  { name: "Axel", slot: "Backpack", quality: "Named" },
  { name: "Backbone", slot: "Backpack", quality: "Named" },
  { name: "Battery Pack", slot: "Backpack", quality: "Named" },
  { name: "Bulldog", slot: "Backpack", quality: "Named" },
  { name: "Cap’n", slot: "Backpack", quality: "Named" },
  { name: "Devil's Due", slot: "Backpack", quality: "Named" },
  { name: "Festive Delivery", slot: "Backpack", quality: "Named" },
  { name: "Force Multiplier", slot: "Backpack", quality: "Named" },
  { name: "Hermano", slot: "Backpack", quality: "Named" },
  { name: "Lavoisier", slot: "Backpack", quality: "Named" },
  { name: "Liquid Engineer", slot: "Backpack", quality: "Named" },
  { name: "Matador", slot: "Backpack", quality: "Named" },
  { name: "Momma Badger", slot: "Backpack", quality: "Named" },
  { name: "Percussive Maintenance", slot: "Backpack", quality: "Named" },
  { name: "Proxy", slot: "Backpack", quality: "Named" },
  { name: "Strategic Alignment", slot: "Backpack", quality: "Named" },
  { name: "The Courier", slot: "Backpack", quality: "Named" },
  { name: "The Gift", slot: "Backpack", quality: "Named" },
  { name: "The Setup", slot: "Backpack", quality: "Named" },
  { name: "Vigil", slot: "Backpack", quality: "Named" },
  { name: "Benefactor", slot: "Chest", quality: "Named" },
  { name: "Bober", slot: "Chest", quality: "Named" },
  { name: "Caesar's Guard", slot: "Chest", quality: "Named" },
  { name: "Carpenter", slot: "Chest", quality: "Named" },
  { name: "Chainkiller", slot: "Chest", quality: "Named" },
  { name: "Cherished", slot: "Chest", quality: "Named" },
  { name: "Closer", slot: "Chest", quality: "Named" },
  { name: "Combustor", slot: "Chest", quality: "Named" },
  { name: "Door-Kicker's Knock", slot: "Chest", quality: "Named" },
  { name: "Equalizer", slot: "Chest", quality: "Named" },
  { name: "Everyday Carrier", slot: "Chest", quality: "Named" },
  { name: "Ferocious Calm", slot: "Chest", quality: "Named" },
  { name: "Henri", slot: "Chest", quality: "Named" },
  { name: "Hunter-Killer", slot: "Chest", quality: "Named" },
  { name: "Impetus", slot: "Chest", quality: "Named" },
  { name: "Pointman", slot: "Chest", quality: "Named" },
  { name: "Pristine Example", slot: "Chest", quality: "Named" },
  { name: "Robin", slot: "Chest", quality: "Named" },
  { name: "Sleight", slot: "Chest", quality: "Named" },
  { name: "The Sacrifice", slot: "Chest", quality: "Named" },
  { name: "Vedmedytsya Vest", slot: "Chest", quality: "Named" },
  { name: "Zero F's", slot: "Chest", quality: "Named" },
  { name: "Contractor's Gloves", slot: "Gloves", quality: "Named" },
  { name: "Deathgrips", slot: "Gloves", quality: "Named" },
  { name: "Eagle's Grasp", slot: "Gloves", quality: "Named" },
  { name: "Firm Handshake", slot: "Gloves", quality: "Named" },
  { name: "Motherly Love", slot: "Gloves", quality: "Named" },
  { name: "Ammo Dump", slot: "Holster", quality: "Named" },
  { name: "Claws Out", slot: "Holster", quality: "Named" },
  { name: "Forge", slot: "Holster", quality: "Named" },
  { name: "Picaro's Holster", slot: "Holster", quality: "Named" },
  { name: "Salvo", slot: "Holster", quality: "Named" },
  { name: "Spot-on", slot: "Holster", quality: "Named" },
  { name: "Cloak", slot: "Kneepads", quality: "Named" },
  { name: "Emperor's Guard", slot: "Kneepads", quality: "Named" },
  { name: "Fox's Prayer", slot: "Kneepads", quality: "Named" },
  { name: "Grease", slot: "Kneepads", quality: "Named" },
  { name: "Snow Machine", slot: "Kneepads", quality: "Named" },
  { name: "Turmoil", slot: "Kneepads", quality: "Named" },
  { name: "Chill Out", slot: "Mask", quality: "Named" },
  { name: "Nightwatcher", slot: "Mask", quality: "Named" },
  { name: "Punch Drunk", slot: "Mask", quality: "Named" },
  { name: "The Hollow Man", slot: "Mask", quality: "Named" },
  { name: "Visionario", slot: "Mask", quality: "Named" },
];

export type TalentKind = "weapon" | "gear";

export type TalentQuality = "Exotic" | "Gear Set" | "Named" | "Standard";

export interface CatalogTalent {
  name: string;
  kind: TalentKind;
  quality: TalentQuality;
}

/** Weapon and gear talents (360), deduplicated by kind and name. */
export const TALENTS: readonly CatalogTalent[] = [
  { name: "Ablative Nano-Plating", kind: "gear", quality: "Exotic" },
  { name: "Abridged", kind: "gear", quality: "Exotic" },
  { name: "Accelerando", kind: "gear", quality: "Gear Set" },
  { name: "Ace in the Sleeve", kind: "gear", quality: "Gear Set" },
  { name: "Adrenaline Rush", kind: "gear", quality: "Standard" },
  { name: "Aggressive Recon", kind: "gear", quality: "Gear Set" },
  { name: "All for One", kind: "gear", quality: "Gear Set" },
  { name: "Alternating Current", kind: "gear", quality: "Exotic" },
  { name: "Apex Predator", kind: "gear", quality: "Gear Set" },
  { name: "Best Buds", kind: "gear", quality: "Gear Set" },
  { name: "Bewildered", kind: "gear", quality: "Named" },
  { name: "Bleeding Edge", kind: "gear", quality: "Exotic" },
  { name: "Blessed", kind: "gear", quality: "Gear Set" },
  { name: "Bloodsucker", kind: "gear", quality: "Standard" },
  { name: "Bob and Weave", kind: "gear", quality: "Exotic" },
  { name: "Bond", kind: "gear", quality: "Exotic" },
  { name: "Braced", kind: "gear", quality: "Standard" },
  { name: "Calculated", kind: "gear", quality: "Standard" },
  { name: "Camaraderie", kind: "gear", quality: "Gear Set" },
  { name: "Chain Combustion", kind: "gear", quality: "Gear Set" },
  { name: "Challenger", kind: "gear", quality: "Exotic" },
  { name: "Charging \\ Charged", kind: "gear", quality: "Gear Set" },
  { name: "Chemical Agent", kind: "gear", quality: "Exotic" },
  { name: "Clutch", kind: "gear", quality: "Standard" },
  { name: "Cold", kind: "gear", quality: "Gear Set" },
  { name: "Combat Medic", kind: "gear", quality: "Exotic" },
  { name: "Combined Arms", kind: "gear", quality: "Standard" },
  { name: "Companion", kind: "gear", quality: "Standard" },
  { name: "Compiler Optimization", kind: "gear", quality: "Gear Set" },
  { name: "Complete Uptime", kind: "gear", quality: "Gear Set" },
  { name: "Composure", kind: "gear", quality: "Standard" },
  { name: "Concussion", kind: "gear", quality: "Standard" },
  { name: "Core Exercise", kind: "gear", quality: "Gear Set" },
  { name: "Counter", kind: "gear", quality: "Exotic" },
  { name: "Creeping Death", kind: "gear", quality: "Standard" },
  { name: "Critical Measures", kind: "gear", quality: "Gear Set" },
  { name: "Daring", kind: "gear", quality: "Gear Set" },
  { name: "Dead Man's Hand", kind: "gear", quality: "Gear Set" },
  { name: "Deceit", kind: "gear", quality: "Gear Set" },
  { name: "Defibrillator", kind: "gear", quality: "Exotic" },
  { name: "Dragon's Glare", kind: "gear", quality: "Exotic" },
  { name: "Efficient", kind: "gear", quality: "Standard" },
  { name: "Empathic Resolve", kind: "gear", quality: "Standard" },
  { name: "Endless Hunger", kind: "gear", quality: "Gear Set" },
  { name: "Energize", kind: "gear", quality: "Standard" },
  { name: "Entrench", kind: "gear", quality: "Standard" },
  { name: "Escape Plan", kind: "gear", quality: "Exotic" },
  { name: "Explosive Delivery", kind: "gear", quality: "Standard" },
  { name: "Feedback Loop", kind: "gear", quality: "Gear Set" },
  { name: "Fireworks Show", kind: "gear", quality: "Named" },
  { name: "Flurry", kind: "gear", quality: "Named" },
  { name: "Focus", kind: "gear", quality: "Standard" },
  { name: "Fortissimo", kind: "gear", quality: "Gear Set" },
  { name: "From The Shadows", kind: "gear", quality: "Gear Set" },
  { name: "From the Shadows \\ Into the Light", kind: "gear", quality: "Gear Set" },
  { name: "Galvanize", kind: "gear", quality: "Standard" },
  { name: "Glass Cannon", kind: "gear", quality: "Standard" },
  { name: "Ground Control", kind: "gear", quality: "Gear Set" },
  { name: "Gunslinger", kind: "gear", quality: "Standard" },
  { name: "Hackstep Protocol", kind: "gear", quality: "Gear Set" },
  { name: "Headache", kind: "gear", quality: "Gear Set" },
  { name: "Headhunter", kind: "gear", quality: "Standard" },
  { name: "Heartstopper", kind: "gear", quality: "Gear Set" },
  { name: "Heatstroke", kind: "gear", quality: "Gear Set" },
  { name: "Hivemind", kind: "gear", quality: "Gear Set" },
  { name: "Hoarder", kind: "gear", quality: "Exotic" },
  { name: "Hostile Negotiations", kind: "gear", quality: "Gear Set" },
  { name: "Huddle", kind: "gear", quality: "Gear Set" },
  { name: "Impervious", kind: "gear", quality: "Exotic" },
  { name: "Improved Dampeners", kind: "gear", quality: "Gear Set" },
  { name: "Improved Materials", kind: "gear", quality: "Gear Set" },
  { name: "Increased Interest", kind: "gear", quality: "Gear Set" },
  { name: "Indirect Transmission", kind: "gear", quality: "Gear Set" },
  { name: "Inner Core", kind: "gear", quality: "Gear Set" },
  { name: "Intimidate", kind: "gear", quality: "Standard" },
  { name: "Into The Light", kind: "gear", quality: "Gear Set" },
  { name: "Iron Grip", kind: "gear", quality: "Exotic" },
  { name: "Just to keep the initial order", kind: "gear", quality: "Exotic" },
  { name: "Just to keep the initial orderer", kind: "gear", quality: "Exotic" },
  { name: "Kill Confirmed", kind: "gear", quality: "Exotic" },
  { name: "Kinetic Momentum", kind: "gear", quality: "Standard" },
  { name: "Leadership", kind: "gear", quality: "Standard" },
  { name: "Mad Bomber", kind: "gear", quality: "Standard" },
  { name: "Makeshift Repairs", kind: "gear", quality: "Gear Set" },
  { name: "Max BPM", kind: "gear", quality: "Gear Set" },
  { name: "Multithreaded Execution", kind: "gear", quality: "Gear Set" },
  { name: "No Limit", kind: "gear", quality: "Gear Set" },
  { name: "Obliterate", kind: "gear", quality: "Standard" },
  { name: "On Point", kind: "gear", quality: "Gear Set" },
  { name: "One for All", kind: "gear", quality: "Gear Set" },
  { name: "One in Hand...", kind: "gear", quality: "Exotic" },
  { name: "Opportunistic", kind: "gear", quality: "Standard" },
  { name: "Ortiz Incinerator Turret Prototype", kind: "gear", quality: "Gear Set" },
  { name: "Ortiz Rapid Application Nanite Prototype", kind: "gear", quality: "Gear Set" },
  { name: "Ostracize", kind: "gear", quality: "Exotic" },
  { name: "Outer Core", kind: "gear", quality: "Gear Set" },
  { name: "Over-engineered", kind: "gear", quality: "Gear Set" },
  { name: "Overcharged Nanites", kind: "gear", quality: "Gear Set" },
  { name: "Overcharging", kind: "gear", quality: "Gear Set" },
  { name: "Overclock", kind: "gear", quality: "Standard" },
  { name: "Overwatch", kind: "gear", quality: "Standard" },
  { name: "Overwhelming Force", kind: "gear", quality: "Gear Set" },
  { name: "Pack Instincts", kind: "gear", quality: "Exotic" },
  { name: "Parabellum Rounds", kind: "gear", quality: "Gear Set" },
  { name: "Parkour!", kind: "gear", quality: "Exotic" },
  { name: "Patriotic Boost", kind: "gear", quality: "Gear Set" },
  { name: "Perfect Adrenaline Rush", kind: "gear", quality: "Named" },
  { name: "Perfect Bloodsucker", kind: "gear", quality: "Named" },
  { name: "Perfect Braced", kind: "gear", quality: "Named" },
  { name: "Perfect Clutch", kind: "gear", quality: "Named" },
  { name: "Perfect Combined Arms", kind: "gear", quality: "Named" },
  { name: "Perfect Companion", kind: "gear", quality: "Named" },
  { name: "Perfect Composure", kind: "gear", quality: "Named" },
  { name: "Perfect Creeping Death", kind: "gear", quality: "Named" },
  { name: "Perfect Empathic Resolve", kind: "gear", quality: "Named" },
  { name: "Perfect Energize", kind: "gear", quality: "Named" },
  { name: "Perfect Entrench", kind: "gear", quality: "Named" },
  { name: "Perfect Focus", kind: "gear", quality: "Named" },
  { name: "Perfect Galvanize", kind: "gear", quality: "Named" },
  { name: "Perfect Glass Cannon", kind: "gear", quality: "Named" },
  { name: "Perfect Gunslinger", kind: "gear", quality: "Named" },
  { name: "Perfect Headhunter", kind: "gear", quality: "Named" },
  { name: "Perfect Intimidate", kind: "gear", quality: "Named" },
  { name: "Perfect Kinetic Momentum", kind: "gear", quality: "Named" },
  { name: "Perfect Leadership", kind: "gear", quality: "Named" },
  { name: "Perfect Obliterate", kind: "gear", quality: "Named" },
  { name: "Perfect Overclock", kind: "gear", quality: "Named" },
  { name: "Perfect Overwatch", kind: "gear", quality: "Named" },
  { name: "Perfect Protected Reload", kind: "gear", quality: "Named" },
  { name: "Perfect Safeguard", kind: "gear", quality: "Named" },
  { name: "Perfect Shock and Awe", kind: "gear", quality: "Named" },
  { name: "Perfect Spark", kind: "gear", quality: "Named" },
  { name: "Perfect Spotter", kind: "gear", quality: "Named" },
  { name: "Perfect Tech Support", kind: "gear", quality: "Named" },
  { name: "Perfect Trauma", kind: "gear", quality: "Named" },
  { name: "Perfect Vanguard", kind: "gear", quality: "Named" },
  { name: "Perfect Versatile", kind: "gear", quality: "Named" },
  { name: "Perfect Vigilance", kind: "gear", quality: "Named" },
  { name: "Perfectly Calculated", kind: "gear", quality: "Named" },
  { name: "Perfectly Efficient", kind: "gear", quality: "Named" },
  { name: "Perfectly Explosive Delivery", kind: "gear", quality: "Named" },
  { name: "Perfectly Mad Bomber", kind: "gear", quality: "Named" },
  { name: "Perfectly Opportunistic", kind: "gear", quality: "Named" },
  { name: "Perfectly Skilled", kind: "gear", quality: "Named" },
  { name: "Perfectly Tamper Proof", kind: "gear", quality: "Named" },
  { name: "Perfectly Unbreakable", kind: "gear", quality: "Named" },
  { name: "Perfectly Unstoppable Force", kind: "gear", quality: "Named" },
  { name: "Perfectly Wicked", kind: "gear", quality: "Named" },
  { name: "Point of Honor", kind: "gear", quality: "Gear Set" },
  { name: "Point of no Return", kind: "gear", quality: "Gear Set" },
  { name: "Polyethylene Plating", kind: "gear", quality: "Gear Set" },
  { name: "Positive Reinforcement", kind: "gear", quality: "Gear Set" },
  { name: "Press the Advantage", kind: "gear", quality: "Gear Set" },
  { name: "Process Refinery", kind: "gear", quality: "Gear Set" },
  { name: "Proliferation", kind: "gear", quality: "Gear Set" },
  { name: "Protected Reload", kind: "gear", quality: "Standard" },
  { name: "Protector", kind: "gear", quality: "Standard" },
  { name: "Quick Draw", kind: "gear", quality: "Exotic" },
  { name: "Reassigned", kind: "gear", quality: "Standard" },
  { name: "Rebalance", kind: "gear", quality: "Exotic" },
  { name: "Red, White and Blue", kind: "gear", quality: "Gear Set" },
  { name: "Resourceful", kind: "gear", quality: "Exotic" },
  { name: "Return to Sender", kind: "gear", quality: "Gear Set" },
  { name: "Risk Management", kind: "gear", quality: "Gear Set" },
  { name: "Rules of Engagement", kind: "gear", quality: "Gear Set" },
  { name: "Safe Charging", kind: "gear", quality: "Gear Set" },
  { name: "Safeguard", kind: "gear", quality: "Standard" },
  { name: "Seeing Red", kind: "gear", quality: "Exotic" },
  { name: "Shock and Awe", kind: "gear", quality: "Standard" },
  { name: "Short Circuit", kind: "gear", quality: "Gear Set" },
  { name: "Signature Moves", kind: "gear", quality: "Gear Set" },
  { name: "Skilled", kind: "gear", quality: "Standard" },
  { name: "Slotted", kind: "gear", quality: "Exotic" },
  { name: "Smart Cooperation", kind: "gear", quality: "Gear Set" },
  { name: "Smoke Screen", kind: "gear", quality: "Exotic" },
  { name: "Snowball", kind: "gear", quality: "Gear Set" },
  { name: "Spark", kind: "gear", quality: "Standard" },
  { name: "Specialized Destruction", kind: "gear", quality: "Gear Set" },
  { name: "Spotter", kind: "gear", quality: "Standard" },
  { name: "Stand Your Ground", kind: "gear", quality: "Exotic" },
  { name: "Stoic", kind: "gear", quality: "Gear Set" },
  { name: "Strategic Combat Support", kind: "gear", quality: "Gear Set" },
  { name: "Striker's Gamble", kind: "gear", quality: "Gear Set" },
  { name: "Sustainability", kind: "gear", quality: "Gear Set" },
  { name: "Symphony", kind: "gear", quality: "Gear Set" },
  { name: "Symptom Aggravator", kind: "gear", quality: "Gear Set" },
  { name: "Tactical Superiority", kind: "gear", quality: "Gear Set" },
  { name: "Tag Team", kind: "gear", quality: "Standard" },
  { name: "Tamper Proof", kind: "gear", quality: "Standard" },
  { name: "Target Rich Environment", kind: "gear", quality: "Gear Set" },
  { name: "Tech Support", kind: "gear", quality: "Standard" },
  { name: "Tend and Befriend", kind: "gear", quality: "Gear Set" },
  { name: "Throttle Control", kind: "gear", quality: "Gear Set" },
  { name: "Toxic Delivery", kind: "gear", quality: "Exotic" },
  { name: "Transference Overclock", kind: "gear", quality: "Exotic" },
  { name: "Trauma", kind: "gear", quality: "Standard" },
  { name: "Trauma Specialist", kind: "gear", quality: "Gear Set" },
  { name: "Unbreakable", kind: "gear", quality: "Standard" },
  { name: "Unstoppable Force", kind: "gear", quality: "Standard" },
  { name: "Vanguard", kind: "gear", quality: "Standard" },
  { name: "Versatile", kind: "gear", quality: "Standard" },
  { name: "Vicious Cycle", kind: "gear", quality: "Exotic" },
  { name: "Vigilance", kind: "gear", quality: "Standard" },
  { name: "Waving the Flag", kind: "gear", quality: "Gear Set" },
  { name: "Weakest Link", kind: "gear", quality: "Exotic" },
  { name: "Wicked", kind: "gear", quality: "Standard" },
  { name: "Actum Est", kind: "weapon", quality: "Exotic" },
  { name: "Adaptive Instincts", kind: "weapon", quality: "Exotic" },
  { name: "Agonizing Bite", kind: "weapon", quality: "Exotic" },
  { name: "Ardent", kind: "weapon", quality: "Exotic" },
  { name: "Autentico", kind: "weapon", quality: "Exotic" },
  { name: "Back and Forth", kind: "weapon", quality: "Standard" },
  { name: "Behind You", kind: "weapon", quality: "Standard" },
  { name: "Big Game Hunter", kind: "weapon", quality: "Exotic" },
  { name: "Binary Trigger", kind: "weapon", quality: "Exotic" },
  { name: "Blossom Harvest", kind: "weapon", quality: "Named" },
  { name: "Boomerang", kind: "weapon", quality: "Standard" },
  { name: "Brazen", kind: "weapon", quality: "Standard" },
  { name: "Breadbasket", kind: "weapon", quality: "Standard" },
  { name: "Breathe Free", kind: "weapon", quality: "Exotic" },
  { name: "Bullet Hell", kind: "weapon", quality: "Exotic" },
  { name: "Busy Little Bee", kind: "weapon", quality: "Exotic" },
  { name: "Caduceus", kind: "weapon", quality: "Exotic" },
  { name: "Capacitance", kind: "weapon", quality: "Exotic" },
  { name: "Capitulate", kind: "weapon", quality: "Exotic" },
  { name: "Close & Personal", kind: "weapon", quality: "Standard" },
  { name: "Cover Shooter", kind: "weapon", quality: "Exotic" },
  { name: "Determined", kind: "weapon", quality: "Standard" },
  { name: "Disruptor Rounds", kind: "weapon", quality: "Exotic" },
  { name: "Doctor Home", kind: "weapon", quality: "Exotic" },
  { name: "Eagle's Strike", kind: "weapon", quality: "Exotic" },
  { name: "Electromagnetic Accelerator", kind: "weapon", quality: "Exotic" },
  { name: "Eyeless", kind: "weapon", quality: "Standard" },
  { name: "Fast Hands", kind: "weapon", quality: "Standard" },
  { name: "Faster Than Reloading", kind: "weapon", quality: "Exotic" },
  { name: "Finisher", kind: "weapon", quality: "Standard" },
  { name: "First Blood", kind: "weapon", quality: "Standard" },
  { name: "Flatline", kind: "weapon", quality: "Standard" },
  { name: "Frenzy", kind: "weapon", quality: "Standard" },
  { name: "Full Stop", kind: "weapon", quality: "Exotic" },
  { name: "Future Perfect", kind: "weapon", quality: "Standard" },
  { name: "Future Perfection", kind: "weapon", quality: "Named" },
  { name: "Gangland Hit", kind: "weapon", quality: "Exotic" },
  { name: "Geri and Freki", kind: "weapon", quality: "Exotic" },
  { name: "Head Scratcher", kind: "weapon", quality: "Standard" },
  { name: "Hidden Rock", kind: "weapon", quality: "Named" },
  { name: "High Priority Target", kind: "weapon", quality: "Exotic" },
  { name: "Ignited", kind: "weapon", quality: "Standard" },
  { name: "Immobilize", kind: "weapon", quality: "Standard" },
  { name: "In Plain Sight", kind: "weapon", quality: "Exotic" },
  { name: "In Sync", kind: "weapon", quality: "Standard" },
  { name: "Incessant Chatter", kind: "weapon", quality: "Exotic" },
  { name: "Killer", kind: "weapon", quality: "Standard" },
  { name: "Liberty or Death", kind: "weapon", quality: "Exotic" },
  { name: "Lucky Shot", kind: "weapon", quality: "Standard" },
  { name: "Measured", kind: "weapon", quality: "Standard" },
  { name: "Mosquito Song", kind: "weapon", quality: "Exotic" },
  { name: "Naked", kind: "weapon", quality: "Standard" },
  { name: "Near Sighted", kind: "weapon", quality: "Standard" },
  { name: "On Empty", kind: "weapon", quality: "Standard" },
  { name: "Optimist", kind: "weapon", quality: "Standard" },
  { name: "Ortiz Assault Interface", kind: "weapon", quality: "Exotic" },
  { name: "Outsider", kind: "weapon", quality: "Standard" },
  { name: "Overflowing", kind: "weapon", quality: "Standard" },
  { name: "Overwhelm", kind: "weapon", quality: "Standard" },
  { name: "Pakhan", kind: "weapon", quality: "Exotic" },
  { name: "Payment in Kind", kind: "weapon", quality: "Exotic" },
  { name: "Perfect Allegro", kind: "weapon", quality: "Named" },
  { name: "Perfect Back and Forth", kind: "weapon", quality: "Named" },
  { name: "Perfect Boomerang", kind: "weapon", quality: "Named" },
  { name: "Perfect Brazen", kind: "weapon", quality: "Named" },
  { name: "Perfect Breadbasket", kind: "weapon", quality: "Named" },
  { name: "Perfect Distance", kind: "weapon", quality: "Named" },
  { name: "Perfect Eyeless", kind: "weapon", quality: "Named" },
  { name: "Perfect Fast Hands", kind: "weapon", quality: "Named" },
  { name: "Perfect Finisher", kind: "weapon", quality: "Named" },
  { name: "Perfect First Blood", kind: "weapon", quality: "Named" },
  { name: "Perfect Flatline", kind: "weapon", quality: "Named" },
  { name: "Perfect Frenzy", kind: "weapon", quality: "Named" },
  { name: "Perfect Head Scratcher", kind: "weapon", quality: "Named" },
  { name: "Perfect Immobilize", kind: "weapon", quality: "Named" },
  { name: "Perfect Jazz Hands", kind: "weapon", quality: "Named" },
  { name: "Perfect Killer", kind: "weapon", quality: "Named" },
  { name: "Perfect Lucky Shot", kind: "weapon", quality: "Named" },
  { name: "Perfect Measured - DO NOT USE REPORT ME!!", kind: "weapon", quality: "Named" },
  { name: "Perfect Near Sighted", kind: "weapon", quality: "Named" },
  { name: "Perfect Optimist", kind: "weapon", quality: "Named" },
  { name: "Perfect Outsider", kind: "weapon", quality: "Named" },
  { name: "Perfect Overflowing", kind: "weapon", quality: "Named" },
  { name: "Perfect Overwhelm", kind: "weapon", quality: "Named" },
  { name: "Perfect Perpetuation", kind: "weapon", quality: "Named" },
  { name: "Perfect Precision Strike", kind: "weapon", quality: "Named" },
  { name: "Perfect Preservation", kind: "weapon", quality: "Named" },
  { name: "Perfect Pressure Point", kind: "weapon", quality: "Named" },
  { name: "Perfect Pummel", kind: "weapon", quality: "Named" },
  { name: "Perfect Pumped Up", kind: "weapon", quality: "Named" },
  { name: "Perfect Ranger", kind: "weapon", quality: "Named" },
  { name: "Perfect Reformation", kind: "weapon", quality: "Named" },
  { name: "Perfect Rifleman", kind: "weapon", quality: "Named" },
  { name: "Perfect Sadist", kind: "weapon", quality: "Named" },
  { name: "Perfect Salvage", kind: "weapon", quality: "Named" },
  { name: "Perfect Sledgehammer", kind: "weapon", quality: "Named" },
  { name: "Perfect Soft Spot", kind: "weapon", quality: "Named" },
  { name: "Perfect Spike", kind: "weapon", quality: "Named" },
  { name: "Perfect Stabilize", kind: "weapon", quality: "Named" },
  { name: "Perfect Strained", kind: "weapon", quality: "Named" },
  { name: "Perfect Streamline", kind: "weapon", quality: "Named" },
  { name: "Perfect Thunder Strike", kind: "weapon", quality: "Named" },
  { name: "Perfect Unwavering", kind: "weapon", quality: "Named" },
  { name: "Perfect Vindictive", kind: "weapon", quality: "Named" },
  { name: "Perfectly Accurate", kind: "weapon", quality: "Named" },
  { name: "Perfectly Behind You", kind: "weapon", quality: "Named" },
  { name: "Perfectly Close & Personal", kind: "weapon", quality: "Named" },
  { name: "Perfectly Determined", kind: "weapon", quality: "Named" },
  { name: "Perfectly Extra", kind: "weapon", quality: "Named" },
  { name: "Perfectly Ignited", kind: "weapon", quality: "Named" },
  { name: "Perfectly In Sync", kind: "weapon", quality: "Named" },
  { name: "Perfectly Measured", kind: "weapon", quality: "Named" },
  { name: "Perfectly Naked", kind: "weapon", quality: "Named" },
  { name: "Perfectly On Empty", kind: "weapon", quality: "Named" },
  { name: "Perfectly Optimized", kind: "weapon", quality: "Named" },
  { name: "Perfectly Steady Handed", kind: "weapon", quality: "Named" },
  { name: "Perfectly Unhinged", kind: "weapon", quality: "Named" },
  { name: "Perpetuation", kind: "weapon", quality: "Standard" },
  { name: "Perturb", kind: "weapon", quality: "Exotic" },
  { name: "Plague of the Outcasts", kind: "weapon", quality: "Exotic" },
  { name: "Precision Strike", kind: "weapon", quality: "Standard" },
  { name: "Preservation", kind: "weapon", quality: "Standard" },
  { name: "Pressure Point", kind: "weapon", quality: "Standard" },
  { name: "Primer Rounds", kind: "weapon", quality: "Named" },
  { name: "Pummel", kind: "weapon", quality: "Standard" },
  { name: "Pumped Up", kind: "weapon", quality: "Standard" },
  { name: "Ranger", kind: "weapon", quality: "Standard" },
  { name: "Reformation", kind: "weapon", quality: "Standard" },
  { name: "Regicide", kind: "weapon", quality: "Exotic" },
  { name: "Restrained", kind: "weapon", quality: "Exotic" },
  { name: "Rifleman", kind: "weapon", quality: "Standard" },
  { name: "Rule Them All", kind: "weapon", quality: "Exotic" },
  { name: "Sadist", kind: "weapon", quality: "Standard" },
  { name: "Salvage", kind: "weapon", quality: "Standard" },
  { name: "Sandman", kind: "weapon", quality: "Exotic" },
  { name: "Septic Shock", kind: "weapon", quality: "Exotic" },
  { name: "Sledgehammer", kind: "weapon", quality: "Standard" },
  { name: "Soft Spot", kind: "weapon", quality: "Standard" },
  { name: "Spike", kind: "weapon", quality: "Standard" },
  { name: "Sport Mode", kind: "weapon", quality: "Named" },
  { name: "Stabilize", kind: "weapon", quality: "Standard" },
  { name: "Steady Handed", kind: "weapon", quality: "Standard" },
  { name: "Strained", kind: "weapon", quality: "Standard" },
  { name: "Streamline", kind: "weapon", quality: "Standard" },
  { name: "Swift", kind: "weapon", quality: "Named" },
  { name: "Symbiosis", kind: "weapon", quality: "Exotic" },
  { name: "Tenacity", kind: "weapon", quality: "Exotic" },
  { name: "The Trap", kind: "weapon", quality: "Exotic" },
  { name: "Thunder Strike", kind: "weapon", quality: "Standard" },
  { name: "Transfusion", kind: "weapon", quality: "Exotic" },
  { name: "Unhinged", kind: "weapon", quality: "Standard" },
  { name: "Unnerve", kind: "weapon", quality: "Exotic" },
  { name: "Unwavering", kind: "weapon", quality: "Standard" },
  { name: "Vindictive", kind: "weapon", quality: "Standard" },
];

/** Distinct attribute names across gear and weapons (36). */
export const ATTRIBUTES: readonly string[] = [
  "Accuracy",
  "Ammo Capacity",
  "Armor on Kill %",
  "Armor Regeneration",
  "Armor Regeneration %",
  "Critical Hit Chance",
  "Critical Hit Damage",
  "Damage to Armor",
  "Damage to TOC",
  "Explosive Resistance",
  "Hazard Protection",
  "Headshot Damage",
  "Health",
  "Health Damage",
  "Incoming Repairs",
  "Mag Size %",
  "Magazine Size %",
  "Melee Damage",
  "Optimal Range",
  "Pistol Damage",
  "Rate of Fire %",
  "Reduced Threat",
  "Reload Speed %",
  "Repair Skills",
  "Scanner Pulse Haste",
  "Shield Health",
  "Skill Damage",
  "Skill Efficiency",
  "Skill Haste",
  "Skill Health",
  "Skill Tier",
  "Stability",
  "Status Effects",
  "Swap Speed",
  "Weapon Damage",
  "Weapon Handling",
];
